### ISSUE TITLE
Autocomplete not working, but different issue than #2

### ISSUE THREAD

**Issue by saagarjha** [johncsnyder/SwiftKitten#3]
Like issue #2, autocomplete doesn't work for me, except the errors I'm getting are different. Here are the logs:

First, when loading:
 `WARNING:root:failed to import yajl2_cffi backend for ijson. reverting to pure python backend.`
(even after following directions to build)

After every keypress, I get:

```
Traceback (most recent call last):
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/SwiftKitten/SwiftKitten.py", line 160, in handle_timeout
    self.handle_timeout(view)
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/SwiftKitten/SwiftKitten.py", line 112, in handle_timeout
    self.on_idle(view)
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/SwiftKitten/SwiftKitten.py", line 118, in on_idle
    structure_info = self._get_structure_info(view)
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/SwiftKitten/SwiftKitten.py", line 281, in _get_structure_info
    cmd = self.get_structure_info_cmd(view, text)
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/SwiftKitten/SwiftKitten.py", line 269, in get_structure_info_cmd
    "sourcekitten_binary", "sourcekitten")
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/SwiftKitten/SwiftKitten.py", line 244, in get_settings
    return project_data.get(key, settings.get(key, default))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by johncsnyder** [comment]
When you open Sublime with no project file, then `project_data` returns None. I'll add a fix for this.

**Comment by saagarjha** [comment]
Would `project_data = view.window().project_data() or {}` be a good enough fix?

**Comment by peymankh4** [comment]
Also getting the same issue on Build 3114.

**Comment by gordio** [comment]
Getting the same issue on ST3 Build 3126. No project, learn swift with single file and cli.
